version: "3.9"
services:

  shippingservice:
    image: vhiveease/onlineshop-shippingservice:latest
    container_name: 'shippingservice'
    build:
      context: ./../../shippingservice/
      dockerfile: ./Dockerfile
    environment:
      - PORT=50051
      - DISABLE_PROFILER=true
      - DISABLE_DEBUGGER=true
      - DISABLE_TRACING=true
    ports:
    - target: 50051


  relay:
    image: vhiveease/relay:latest
    entrypoint:
      - /app/server
      - --addr=0.0.0.0:50000
      - --function-endpoint-url=shippingservice
      - --function-endpoint-port=50051
      - --function-name=shippingservice
      - --generator=unique
      - --function-method=ShipOrder
    ports:
      - published: 50000
        target: 50000