# MIT License

# Copyright (c) 2022 EASE lab

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: "3.9"
services:
  fibonacci-python:
    image: vhiveease/fibonacci-python:latest
    container_name: fibonacci-python
    # add host directory so you can write trace file to 
    #entrypoint: /bin/sh -c " /pin/pin -t /pin/tracer/obj-intel64/champsim_tracer.so -o trace.champsim -t 10000000 -p 1 -- /python/bin/python3.11 /app/server.py --addr=0.0.0.0 --port=50051"
    entrypoint:
     - tail 
     - -f
     - /dev/null
    ports:
      - target: 50051

  relay:
    image: vhiveease/relay:latest
    entrypoint:
      - /app/server
      - --addr=0.0.0.0:50000
      - --function-endpoint-url=fibonacci-python
      - --function-endpoint-port=50051
      - --function-name=fibonacci-python
      - --value=10
      - --generator=linear
      - --lowerBound=1
      - --upperBound=10
    ports:
        - published: 50000
          target: 50000